name: tagpr
on:
  push:
    branches: ["main"]
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add reviewer to tagpr PR
      if: github.event_name == 'push'
      run: |
        # tagprが作成したPRを取得
        PR_NUMBER=$(gh pr list --author "github-actions[bot]" --label "tagpr" --state "open" --limit 1 --json number --jq '.[0].number')
        if [ ! -z "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
          gh pr edit $PR_NUMBER --add-reviewer takashabe
          gh pr merge $PR_NUMBER --auto --squash
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}